use customer_behavior;
-- Q1 what is the total revenue generated by male vs female customer?
SELECT	
	gender,sum(purchase_amount) as "Total Revenue"
FROM customer_info
GROUP BY gender;

-- q2 which customer used a discount but still spend more than aveage purchase amount
SELECT 
	customer_id, purchase_amount
FROM customer_info
WHERE discount_applied = "Yes" and purchase_amount > (SELECT avg(purchase_amount) FROM customer_info) ;

-- q3 which are the top 5 products with highest average review rating
SELECT
	item_purchased,
    round(avg(review_rating),2) as "avg_review_rating"
FROM customer_info
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;

-- q4 Compare the avg purchase amounts between standard and express shipping
SELECT 
	shipping_type,round(avg(purchase_amount),2) as "Avg_purchase_amount"
FROM customer_info
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- q5  Compare avg spend and total revenue b/w subscirber and non-subscriber
SELECT 
	subscription_status,
    count(DISTINCT customer_id) as "Total Customers",
    round(avg(purchase_amount),2) as "avg_spend",
    round(sum(purchase_amount),2) as "total spend"
FROM customer_info
GROUP BY subscription_status;


-- q6 which 5 products have the highest percentage of purchase with discount applied?
SELECT
	item_purchased, round((count(item_purchased) /(select count(item_purchased) FROM customer_info)) *100,2) as "Purchased %"
FROM customer_info
where discount_applied = "Yes"
GROUP BY item_purchased
ORDER BY count(item_purchased) DESC
LIMIT 5;

-- q7 segment customers into New, returning Loyal based on their total no of previous puchases, and show the count of each segment

with customer_type As 
(
SELECT
	CASE WHEN previous_purchases = 1 THEN "New"
		WHEN previous_purchases <= 10 THEN "Returning"
        ELSE "Loyal"
	END as customer_segment,
    customer_id
    FROM customer_info
)
SELECT customer_segment,
	count(DISTINCT customer_id) as "customer_count"
FROM customer_type
GROUP BY customer_segment;

-- what are top 3 most purchased products within each cateogry
with item_count as (
SELECT 
	category,item_purchased, count(customer_id) as "purchased_count",
    ROW_NUMBER() over(PARTITION BY category order by count(customer_id) DESC) as "product_rank"
FROM customer_info
GROUP BY category,item_purchased)
SELECT 
	product_rank,category, item_purchased,purchased_count
from item_count
WHERE product_rank <=3;

-- q9 Are customers who are repeat buyers (having more than 5 previous purchases) are more likely to subscribe?
SELECT
	subscription_status,
    count(customer_id)
FROM customer_info
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- q10 what is the revenue contribution of each age group?
SELECT
	age_group,
    round((sum(purchase_amount)/(select sum(purchase_amount) from customer_info))*100,2) as "revenue %"
FROM customer_info
GROUP BY age_group;